- type: replace
  path: /releases/-
  value:
    name: routing # https://github.com/cloudfoundry-incubator/routing-release/releases
    version: 0.162.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.162.0
    sha1: f17cf09d2414f5f486d18bbd57b17fd48fb69773

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment))
    properties:
      route_registrar:
        routes:
        - name: ((bosh_deployment))
          uris:
          - ((bosh_deployment)).((cf_apps_domain))
          port: 15672
          registration_interval: 30s
        - name: ((bosh_deployment))-netdata
          uris:
          - ((bosh_deployment))-netdata.((cf_apps_domain))
          port: 19999
          registration_interval: 30s
          prepend_instance_index: true
