- type: replace
  path: /releases/-
  value:
    name: routing # https://github.com/cloudfoundry-incubator/routing-release/releases
    version: 0.172.0
    url: https://github.com/cloudfoundry/routing-release/releases
    sha1: fa6b0966e38b4089e0565fcab8bf09035ab43778

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment))
    properties:
      route_registrar:
        routes:
        - name: rabbitmq_management-((bosh_deployment))
          uris:
          - ((bosh_deployment)).((cf_apps_domain))
          port: 15672
          registration_interval: 10s
          health_check:
            name: rabbitmq_management-((bosh_deployment))
            script_path: /var/vcap/jobs/rabbitmq-server/bin/rabbitmq_management_http_ok
        - name: netdata-((bosh_deployment))
          uris:
          - netdata-((bosh_deployment)).((cf_apps_domain))
          port: 19999
          registration_interval: 10s
          health_check:
            name: netdata-((bosh_deployment))
            script_path: /var/vcap/jobs/netdata/bin/netdata_http_ok
          prepend_instance_index: true
